### ISSUE TITLE
Turn off device

### ISSUE THREAD

**Issue by sedrubal** [guardianproject/Ripple#12]
It should be possible to turn off the device automatically after all other actions have finished. Then the device encryption will protect the device.

**Comment by abeluck** [comment]
Unfortunately this is not possible on non-rooted devices. An app cannot shutdown/reboot the device in Android.

**Comment by eighthave** [comment]
It should be quite easy to make a panic responder app that does this, as long as it has root.  That would then receive the trigger from Ripple or another panic trigger app. Ripple is just the trigger, it only manages and sends the trigger message.
