### ISSUE TITLE
Is Ripple dead? 

### ISSUE THREAD

**Issue by ian-tedesco** [guardianproject/Ripple#13]
Hello people, first of all I wanted to say thanks for creating such a wonderful application, please don't stop.

Second of all, if the software is not dead, is there a list of supported applications? Also, what are the limits of Ripple? For example, can uninstall an app? Delete its content? What?

**Comment by abeluck** [comment]
Ripple is not dead nor abandoned, but it isn't exactly seeing much love these days.

AFAIK we do not have a list of applications that support Ripple out of the box. Perhaps @n8fr8  and @eighthave could chime in with a list of apps they know support Ripple.

The major limitations of Ripple are limitations of the Android system itself when it comes to normal apps:

* Cannot uninstall other apps without user interaction for each app
* Cannot remove private app data from other apps (unles the app supports Ripple)
* Cannot turn off nor reboot the device

**Comment by eighthave** [comment]
Ripple hasn't changed because it is functionally complete and there
aren't any known problems.  Ripple is just the trigger, what that
trigger does is up to the responder apps.  For example, if you have
F-Droid built into your ROM with privileged extension, then it can
uninstall apps.  Apps that receive a panic trigger can and do remove
private data.

**Comment by ian-tedesco** [comment]
> Ripple is not dead nor abandoned, but it isn't exactly seeing much love these days.

That's great, I understand that, I'm trying to convince as many devs as I can to add support for the application, below is the list of issues I've created if you are interested to see any updates (if there's any; so far two have accepted).

https://github.com/beemdevelopment/Aegis/issues/312
https://github.com/ccrama/Slide/issues/3127
https://github.com/k9mail/k-9/issues/4561
https://github.com/Kunzisoft/KeePassDX/issues/475
https://gitlab.com/AuroraOSS/AuroraStore/issues/318
https://git.jami.net/savoirfairelinux/ring-client-android/issues/704
https://gitlab.com/gdroid/gdroidclient/issues/775
https://gitlab.com/juanitobananas/scrambled-exif/issues/32

> AFAIK we do not have a list of applications that support Ripple out of the box. Perhaps @n8fr8 and @eighthave could chime in with a list of apps they know support Ripple.

That would be great, AFAIK from using Ripple the only applications that show up are F-droid, Session, Signal, New Pipe, Briar, Silence and Tor Browser.  Do you think a list with supported applications could be added in the README or somewhere either on Ripple's web page or here on GitHub?

> The major limitations of Ripple are limitations of the Android system itself when it comes to normal apps:
> 
>     * Cannot uninstall other apps without user interaction for each app
> 
>     * Cannot remove private app data from other apps (unles the app supports Ripple)
> 
>     * Cannot turn off nor reboot the device

So, if for example, GrapheneOS came with Ripple preinstalled and with root privileges to it, it could turn off/reboot the device?

> Ripple hasn't changed because it is functionally complete and there aren't any known problems. Ripple is just the trigger, what that trigger does is up to the responder apps. For example, if you have F-Droid built into your ROM with privileged extension, then it can uninstall apps. Apps that receive a panic trigger can and do remove private data.

Oh, I see, thanks for letting me know, I was asking because on the first issue I created the developer asked me if your were still supporting it, because they didn't want to add support for it if the project was dead.

**Comment by eighthave** [comment]
Great to see your interest here!  We welcome merge requests everywhere, but please take the time to provide useful information.  For example, this issue is a copy/paste where you didn't even change the app name: https://gitlab.com/juanitobananas/scrambled-exif/issues/32  I can't think of a response the Scrambled EXIF would have for a panic.  You should only file an issue or merge request if you can propose a concrete and realistic response for that specific app.

Please read the PanicKit page to understand the core concepts of Panic Trigger and Panic Responder: https://guardianproject.info/code/panickit/  Its essential but not too complicated.  Ripple is only a single Panic Trigger app, a phone could have multiple with different methods of sending the trigger, as well as a different set of apps that respond to its trigger.

**Comment by ian-tedesco** [comment]
> Great to see your interest here! We welcome merge requests everywhere, but please take the time to provide useful information. For example, this issue is a copy/paste where you didn't even change the app name: https://gitlab.com/juanitobananas/scrambled-exif/issues/32 I can't think of a response the Scrambled EXIF would have for a panic. You should only file an issue or merge request if you can propose a concrete and realistic response for that specific app.
> 
> Please read the PanicKit page to understand the core concepts of Panic Trigger and Panic Responder: https://guardianproject.info/code/panickit/ Its essential but not too complicated. Ripple is only a single Panic Trigger app, a phone could have multiple with different methods of sending the trigger, as well as a different set of apps that respond to its trigger.

Sorry, I was really sleepy when I was filling in the issues, I did copypasted the structure of the text because I think it was not going to differ a lot between applications, but I did tried to look for specific use cases for each one.  I can't think of something that Scrambled EXIF could do besides hiding the app, that's why I left it blank, but I think that's okay, maybe you just want someone to not know you have it installed.

I have read the link you sent my, I'll try to elaborate a bit more if I found another candidate for integration. By the way, in that link you mention that New Pipe deletes search history but when I go to Ripple it just says that it hides the app and there's no "Edit".
