### ISSUE TITLE
Can't build project because of broken locale code

### ISSUE THREAD

**Issue by 8of** [guardianproject/Ripple#7]
**Problem**
Android Studio 3.1.2 doesn't recognize `values-zh-Hans` folder when building app and give me the error:
```
/Ripple/app/src/main/res/values-zh-Hans: Error: Invalid resource directory name
```
**Solution**
Replace `values-zh-Hans` with `values-zh`.
From my understanding of simplified / traditional Chinese language variations this is correct replacement.
**More on the problem**
This guy probably addressed issue the best
https://gist.github.com/amake/0ac7724681ac1c178c6f95a5b09f03ce#new-locales-vs-old-locales-chinese

I'll be happy to fix it in PR

**Comment by eighthave** [comment]
I think you're right that _Hans_ is not a valid value for Android, but _values-zh_ isn't really either.  Based on [this](https://stackoverflow.com/a/17276279) I think it should be _values-zh-rCN_.

**Comment by 8of** [comment]
`values-zh-rCN` gives the same error as `values-zh-Hans` 🤔

**Comment by 8of** [comment]
@eighthave you are right. It works that way.
Also fixed the PR 👍
